### ISSUE TITLE
A problem in loss.py

### ISSUE THREAD

**Issue by Yinyf0804** [sunjesse/SimCLR_pytorch#1]
Hi, thanks for your great code.
I have a problem in loss.py:  In line 17:  den = norm * b * ..... , but in line 23: num = b / norm, i wonder if both of them are b / norm.

**Comment by agil27** [comment]
I have the same question; Below is my math deduction

![](https://i.imgur.com/TTsFIQn.png)

**Comment by fdarbeha** [comment]
Thank you for your question. This issue is fixed now so I will close this thread.
